# Generated by Django 5.1.4 on 2025-04-16 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
